# Setup
title:        unicore-life
tagline:      unicore grid middleware extensions and tools
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       rkluszczynski
  url:        https://github.com/rkluszczynski 

# Gems
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-octicons

#Others
markdown: kramdown
