# Setup
title:        unicore-life
tagline:      unicore grid useful extensions and tools<
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       rkluszczynski
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
